### PR TITLE
Global refactoring of outputs

### LINKED ISSUE #22: Remove `transfer_learning_multicnn` parameter from training
Remove `transfer_learning_multicnn` parameter from training and find if the transfer learning folder is multi or single (automatically).
Suggested in PR #20.

### LINKED ISSUE #26: Clarify the use of the option `transfer_learning_path`
`transfer_learning_path` parameter is not very clear. For subject-level AE it is the path to the model file (filename included) and for others to the root folder of the experiment (the implementation of subject-level AE should be changed).

Suggested in PR #20.

### LINKED ISSUE #30: Autoencoder homogeneization (patch/roi vs image)
The outputs of autoencoders are different depending on the pipeline (pach/roi or image).
Moreover the `visualization` argument should be implemented  in the same way for patch/roi and image.

### PR DESCRIPTION
**Pull request by 14thibea**
This PR intends to refactor the outputs of `clinicadl train` to have more homogeneity between pipelines and outputs less costly to store. 

It closes https://github.com/aramis-lab/AD-DL/issues/22, closes https://github.com/aramis-lab/AD-DL/issues/26, closes https://github.com/aramis-lab/AD-DL/issues/30.

### CODE REVIEW

**Comment by mdiazmel** [comment]
Currently I'm working in the implementation of `clinicadl classify` (PR #34). 
I think that this PR can impact/facilitate the behavior of `classify`.

**Comment by 14thibea** [comment]
Last commit https://github.com/aramis-lab/AD-DL/pull/42/commits/f6cd13d5155e4cee871ff309b6527bf06d22d57a closes https://github.com/aramis-lab/AD-DL/issues/22 and https://github.com/aramis-lab/AD-DL/issues/26

**Comment by 14thibea** [comment]
I did not finish the whole refactoring, but this PR is already too long, so maybe we can stop here.
The most important changes are
- transfer learning homogeneization
- autoencoder training homogeneization
- outputs homogeneization for all pipelines (especially content of .pth.tar files)

**Review by mdiazmel — COMMENTED** [review]
Everything seems fine. I'll run some test in local and the I'll merge.

**Pull request merged**
