### PR TITLE
Verbose

### LINKED ISSUE #62: Implement verbose levels
There are way too many print calls in `clinicadl train`.
A verbose argument could be given to deal with the number of prints
- 0 no print
- 1 default level
- 2 debug print (time for batch loading)

### PR DESCRIPTION
**Pull request by 14thibea**
This PR resolves https://github.com/aramis-lab/AD-DL/issues/62.
The goal of this PR is to print messages with logging:
- messages with level info / debug or less are directed to stdout,
- other messages are directed to stderr. 

Specific loggers are created depending on the function and formatted the message to also print the date + the name of the logger.

### CODE REVIEW

**Comment by 14thibea** [comment]
Once #65 will be merged, adapt the printed messages in classify with logging.
Also remove the folder `test` which will become obsolete.

**Comment by 14thibea** [comment]
Waiting for #71 to be merged to add verbose in transfer learning.

**Comment by mdiazmel** [comment]
Hi @14thibea ,
This PR is still in draft mode... please let me know when it's ready for review !
(Maybe it should be unlinked from PR #71 which will be closed later, according to the roadmap).

**Review by mdiazmel — COMMENTED** [review]
Hi @14thibea ,

Thanks for this PR, it's a huge one ;)

I wonder if it's possible to write the logger output to a file. Maybe this can be helpful for some users. 
Also to format the logger output using time/date format ([see here](https://docs.python.org/3/howto/logging.html#displaying-the-date-time-in-messages)). Well, these modifications can wait to be added in the future PR. For the moment, I'll merge this PR as it is.

**Pull request merged**
