### PR TITLE
Add some instructions to Readme

### PR DESCRIPTION
**Pull request by mdiazmel**
Add a Table of Contents and some examples.

### CODE REVIEW

**Comment by alexandreroutier** [comment]
We should add a small disclaimer explaining that this currently under active development until the first release is done :)

**Comment by mdiazmel** [comment]
Hi @alexandreroutier,

> We should add a small disclaimer explaining that this currently under active development until the first release is done :)

There is already a disclaimer at 3rd paragraph of the "About the project" section. Suggestions on how to improve its visibility are welcome!

**Comment by alexandreroutier** [comment]
> Hi @alexandreroutier,
> 
> > We should add a small disclaimer explaining that this currently under active development until the first release is done :)
> 
> There is already a disclaimer at 3rd paragraph of the "About the project" section. Suggestions on how to improve its visibility are welcome!

My bad, I scrolled too fast 😳 

I would suggest to use `>` for the disclaimer so that it renders like this:
> Disclaimer: this software is in going-on development. Some features can change between different commits. A stable version is planned to be released soon. The release v.0.0.1 corresponds to the date of submission of the publication but in the meanwhile important changes are being done to facilitate the use of the package.

So the "About the project" section will look like shorter than expected.

In the TOC, I think we should add Examples subsections.

I <3 this new readme!

**Comment by mdiazmel** [comment]
> I would suggest to use `>` for the disclaimer so that it renders like this:

Done!

> In the TOC, I think we should add Examples subsections.

Done!

Ready to merge, @alexandreroutier?

**Review by alexandreroutier — APPROVED** [review]
Ready for merge!

**Pull request merged**
