### PR TITLE
[CI] Run tests through GitHub Actions

### PR DESCRIPTION
**Pull request by NicolasGensollen**
This PR proposes to run the tests through GitHub Actions rather than Jenkins (similar to what we did on Clinica a few months ago).

The VM that was used until now is running on CentOS7 and was clearly missing recent updates.
In addition, CentOS7 will be EOL in June 2024 (https://endoflife.date/centos).
Because of these reasons, I created and configured a new VM running on Ubuntu 20.04-lts.
I should have installed the required tools that we use (like dvc, pipx, poetry, miniconda...) but let me know if something is missing.

I also deployed a new GitHub runner on this VM (there is also one deployed on the CentOS VM but the workflows are crashing due to an old version of glibc, I'll delete it later).

This PR proposes to port two tests: `test_cli.py` and `test_tsvtools.py` to Github Actions, making sure that tests with and without access to `clinical_data_ci` are working fine.

If the proposed solution is accepted, I'll port the remaining tests and remove the associated Jenkins pipeline.

I will also need to take a closer look at the machine were are using for testing GPU support to see if we could implement something similar.

### CODE REVIEW

**Comment by NicolasGensollen** [comment]
Here is the result for test_cli: https://github.com/aramis-lab/clinicadl/actions/runs/9111679617/job/25049309668?pr=573

And the one for test_tsvtools: https://github.com/aramis-lab/clinicadl/actions/runs/9111679640/job/25049309674?pr=573

**Review by thibaultdvx — APPROVED** [review]
LGTM @NicolasGensollen, thanks a lot! I can take care of the other tests if you want.

**Comment by NicolasGensollen** [comment]
Thanks for the review @thibaultdvx ! 👍 
I'll take care of the other tests no worries. I still need to deploy runners on the GPU machine (and maybe an aramis workstation), so I don't mind finishing.
@camillebrianceau is this good for you or do you want to take a closer look before we merge ?

**Comment by NicolasGensollen** [comment]
I'm gonna go ahead and merge this.
We can always revert if we don't like it in the end...

**Pull request merged**
